

spring:
  datasource:
    url: jdbc:h2:mem:holidaydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create-drop
    show-sql: true

nager:
  api:
    base-url: https://date.nager.at/api/v3

data-loader:
  active: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
