openapi: 3.0.3
info:
  title: Holiday API
  version: 1.0.0
  description: |
    공휴일 조회·업데이트·삭제 API
servers:
  - url: /api

paths:
  /holidays:
    post:
      summary: 공휴일 목록 조회
      description: |
        `HolidaySearchFilter`로 조건을 지정하여 페이징된 공휴일 목록을 조회합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HolidaySearchFilter'
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
          description: 0부터 시작하는 페이지 인덱스
        - name: size
          in: query
          schema:
            type: integer
            default: 20
            minimum: 1
          description: 페이지당 항목 수
        - name: sort
          in: query
          schema:
            type: array
            items:
              type: string
              example: date,asc
            default: [date,asc]
          style: form
          explode: false
          description: 정렬 기준 `[property, direction]`
      responses:
        '200':
          description: 페이징된 공휴일 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResponseHolidayResponse'
    patch:
      summary: 공휴일 데이터 재동기화 (Upsert)
      description: |
        지정된 국가·연도의 모든 공휴일을 외부 API에서 재조회하여 DB에 덮어씁니다.
      parameters:
        - name: countryCode
          in: query
          required: true
          schema:
            type: string
          description: 국가 코드 (필수)
        - name: year
          in: query
          required: true
          schema:
            type: integer
            minimum: 2020
            maximum: 2025
          description: 연도 (2020–2025, 필수)
      responses:
        '200':
          description: 재동기화 성공 (내용 없음)
    delete:
      summary: 공휴일 데이터 삭제
      description: 지정된 국가·연도의 모든 공휴일을 삭제합니다.
      parameters:
        - name: countryCode
          in: query
          required: true
          schema:
            type: string
          description: 국가 코드 (필수)
        - name: year
          in: query
          required: true
          schema:
            type: integer
          description: 연도 (필수)
      responses:
        '204':
          description: 삭제 성공 (콘텐츠 없음)
        '400':
          description: 잘못된 요청 (국가 코드 없음 등)

components:
  schemas:
    HolidaySearchFilter:
      type: object
      required:
        - countryCode
        - year
      properties:
        countryCode:
          type: string
          description: 조회할 국가 코드
        year:
          type: integer
          format: int32
          description: 조회할 연도 (YYYY)
        startDate:
          type: string
          format: date
          description: 시작일 (ISO 날짜)
        endDate:
          type: string
          format: date
          description: 종료일 (ISO 날짜)
        type:
          $ref: '#/components/schemas/HolidayType'
    HolidayResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        localName:
          type: string
        date:
          type: string
          format: date
        year:
          type: integer
          format: int32
        countryCode:
          type: string
        countryName:
          type: string
        isFixed:
          type: boolean
        isGlobal:
          type: boolean
        types:
          type: array
          items:
            $ref: '#/components/schemas/HolidayType'
    PageInfo:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        currentPage:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        hasNext:
          type: boolean
        hasPrevious:
          type: boolean
    PageResponseHolidayResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/HolidayResponse'
        pageInfo:
          $ref: '#/components/schemas/PageInfo'
    HolidayType:
      type: string
      enum:
        - PUBLIC
        - BANK
        - SCHOOL
        - AUTHORITIES
        - OPTIONAL
        - OBSERVANCE
